### ISSUE TITLE
[BUG] bencode_dict_get_start_and_len asserts if presented with a complex structure

### ISSUE THREAD

**Issue by MrPeach** [willemt/heapless-bencode#3]
bencode_dict_get_start_and_len will assert if presented with a real life torrent file.
The code is not written to perform a recursive walk through all sub-elements.
It can only handle the very simplest of bencode structures.

**Comment by willemt** [comment]
I fuzz tested the library and have since fixed some dict issues. It'll be able to read any torrent file.

```bencode_dict_get_start_and_len``` does do a recursive walk through sub-elements:
https://github.com/willemt/heapless-bencode/blob/master/tests/test_bencode.c#L864
